### ISSUE TITLE
3-6-0脱壳遇到问题

### ISSUE THREAD

**Issue by gttiankai** [bunnyblue/DexExtractor#3]
你好.
首先非常感谢你的脱壳工具.
今天使用你的脱壳工具,脱了一下360的加壳.遇到问题.
报错:
ERROR: couldn't find native method

apk:农行
bug:
07-03 06:07:39.807: E/dalvikvm(2608): --pacthed--  inject  .dex length 2161912 
07-03 06:07:39.817: E/dalvikvm(2608): --pacthed-- , /sdcard/com.android.bankabc_classes_2161912.dex
07-03 06:07:39.817: E/dalvikvm(2608): --pacthed--  debug dalvikParse   find dex try write file  
07-03 06:07:39.847: E/dalvikvm(2608): Unable to delete the file
07-03 06:07:39.997: E/dalvikvm(2608): --pacthed--   create file  /sdcard/com.android.bankabc_classes_2161912.dex 
07-03 06:07:40.497: E/dalvikvm(2608): --pacthed--  create file  end 
07-03 06:07:41.237: E/dalvikvm(2608): ERROR: couldn't find native method
07-03 06:07:41.237: E/dalvikvm(2608): Requested: Lcom/qihoo/util/StubApplication;.interface7:(Landroid/app/Application;Landroid/content/Context;)Z
07-03 06:07:43.887: E/dalvikvm(2608): --pacthed--  inject  .dex length 2161912 
07-03 06:07:43.897: E/dalvikvm(2608): --pacthed-- , /sdcard/com.android.bankabc_classes_2161912.dex
07-03 06:07:43.897: E/dalvikvm(2608): --pacthed--  debug dalvikParse   find dex try write file  
07-03 06:07:43.927: E/dalvikvm(2608): /sdcard/com.android.bankabc_classes_2161912.dex file deleted successfully.
07-03 06:07:43.977: E/dalvikvm(2608): --pacthed--   create file  /sdcard/com.android.bankabc_classes_2161912.dex 
07-03 06:07:44.427: E/dalvikvm(2608): --pacthed--  create file  end

**Comment by bunnyblue** [comment]
360修改了结构体，好像需要运行时处理

**Comment by gttiankai** [comment]
您方便具体的说一下吗？最近在研究一种比较通用的脱壳技术，您的这个技术已经很强了，我想再完善一下。我们也可以私聊。

**Comment by bunnyblue** [comment]
你Google 下 360 脱壳
