### ISSUE TITLE
提取到DEX后decode dex2jar 发现问题

### ISSUE THREAD

**Issue by johnx4** [bunnyblue/DexExtractor#5]
Caused by: java.lang.IllegalArgumentException: bogus opcode: 00f2
    at com.android.dx.io.OpcodeInfo.get(OpcodeInfo.java:1196)
    at com.android.dx.io.OpcodeInfo.getFormat(OpcodeInfo.java:1212)
    at com.android.dx.io.instructions.DecodedInstruction.decode(DecodedInstruction.java:72)
    at jadx.core.dex.instructions.InsnDecoder.decodeInsns(InsnDecoder.java:43)
    ... 6 more

decode方法体内部时会报此种错误 转换为smali后查看发现此种代码  
 #disallowed odex opcode
    #iget-quick v0, p0, field@0x48
    nop

是代码的问题还是工具的bug？？谢谢

**Comment by bunnyblue** [comment]
你看下下时dex还是odex ，odex的话你需要自己转换成dex，有些加固是dex有些是odex

**Comment by johnx4** [comment]
是dex

**Comment by bunnyblue** [comment]
应该是代码问题，感觉加固升级了

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by johnx4** [comment]
https://github.com/skylot/jadx/issues/69
我在这个帖子里面发现了相同的问题，请问是否原本为odex的文件被保存为了dex文件？

**Comment by bunnyblue** [comment]
你看下文件头是035还是036 不要看后缀名

 有一种工作只是工作，有一种工作就是你的生活。
                                                          *Best Regards*

**Comment by johnx4** [comment]
dex 035

**Comment by johnx4** [comment]
最前面还有一段dey 036 我觉得是壳就去掉了

**Comment by bunnyblue** [comment]
dey是odex 你需要转换成dex才行

**Comment by johnx4** [comment]
求教怎么转换？

**Comment by bunnyblue** [comment]
有些dex有些odex 取出来的时候看下文件头

**Comment by bunnyblue** [comment]
http://www.cnblogs.com/wanqieddy/archive/2012/03/01/2375424.html
http://forum.xda-developers.com/galaxy-s2/themes-apps/how-to-manually-deodex-odex-t1208320

**Comment by johnx4** [comment]
十分感谢，有问题再请教
