### ISSUE TITLE
libdvm.so 放到真机后悲剧了

### ISSUE THREAD

**Issue by IDrinkMoreWater** [bunnyblue/DexExtractor#6]
放arm的libdvm.so到中兴手机后出现:DexOpt: build rev does not match VM: 27 vs 28,手痒忘记忘记备份了,看来只有重刷系统了,DALVIK_VM_BUILD 27对应的4.4.2,DALVIK_VM_BUILD 28是什么鬼,实在太崩溃了,想问下如果DALVIK_VM_BUILD 一致的话,libdvm.so可以放到真机么,会不会还有其他坑

**Comment by bunnyblue** [comment]
这个是模拟器上的，你需要放真机的话，把代码patch进去自己编译

**Comment by IDrinkMoreWater** [comment]
好的,非常感谢,模拟器下梆梆加固脱壳无压力,就是模拟器太慢了点,如果要编译真机也得真机的系统版本和下载的Android source 版本一致才不会出问题吧,如果我把真机系统版本刷成和libdvm.so依赖的版本一致应该也可以吧,这样简单点

**Comment by bunnyblue** [comment]
理论上没问题
