### ISSUE TITLE
libdvm.so有安卓版本要求么，

### ISSUE THREAD

**Issue by stayliv3** [bunnyblue/DexExtractor#7]
你好。我在小米2 android 4.4.4 中替换了libdvm.so 。系统无法启动。这个对安卓版本有要求么，或者

system.img 这个文件如何使用有说明文档么。谢谢~~~

**Comment by bunnyblue** [comment]
4.4模拟器 ，这个针对版本。真机上可能不行，厂商可能修改了。 System.img是编译好的模拟器镜像，启动模拟器指定这个镜像即可，注意需要分配sd卡

via CloudMagic for Mac [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.12.46&pv=10.12.0&source=email_footer_2]
On Tue, Jul 12, 2016 at 10:12 AM, stayliv3 <notifications@github.com> wrote:
你好。我在小米2 android 4.4.4 中替换了libdvm.so 。系统无法启动。这个对安卓版本有要求么，或者

system.img 这个文件如何使用有说明文档么。谢谢~~~
